name: Build

on: [pull_request]

env:
  APP_NAME: 'Camera Streamer'
  IDF_TARGET: 'esp32'
  IDF_VERSION: 'v5.5.1'
  IDF_COMPONENT_MANAGER: "1" # whether to enable the component manager or not
  FLASH_TOTAL_OVERRIDE: '2097152' # 2MB flash app partition for main app

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Build Main
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: ${{ env.IDF_VERSION }}
        target: ${{ env.IDF_TARGET }}
        path: '.'

    - name: Determine Size Delta
      uses: esp-cpp/esp-idf-size-delta@v1
      with:
        app_name: ${{ env.APP_NAME }}
        app_path: '.'
        idf_target: ${{ env.IDF_TARGET }}
        idf_version: ${{ env.IDF_VERSION }}
        idf_component_manager: ${{ env.IDF_COMPONENT_MANAGER }}
        flash_total_override: ${{ env.FLASH_TOTAL_OVERRIDE }}
