name: Build and Package Main

on:
  push:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:

env:
  APP_NAME: 'Camera Streamer'
  IDF_VERSION: 'v5.5.1'
  IDF_COMPONENT_MANAGER: "1" # whether to enable the component manager or not
  FLASH_TOTAL_OVERRIDE: '2097152' # 2MB flash app partition for main app

jobs:
  build:

    runs-on: ubuntu-latest
    continue-on-error: false

    strategy:
      fail-fast: false
      matrix:
        include:
          - board: 'timer-cam'
            target: 'esp32'
          - board: 'xiao-esp32s3-sense'
            target: 'esp32s3'

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-tags: true
        ref: ${{ github.ref }}

    - name: Build Main Code (${{ matrix.board }})
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: ${{ env.IDF_VERSION }}
        target: ${{ matrix.target }}
        path: '.'

    - name: Upload Build Outputs (${{ matrix.board }})
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts-${{ matrix.board }}
        path: |
          build/*.bin
          build/*.elf
          build/bootloader/bootloader.bin
          build/partition_table/partition-table.bin
          build/flasher_args.json
          build/flash_args

    - name: Zip up build files for release using matrix board name + release tag name (${{ matrix.board }})
      if: ${{ github.event.release && github.event.action == 'published' }}
      shell: bash
      run: |
        # zip up just the files we uploaded for the release
        zip_name="camera-streamer-${{ matrix.board }}_$(git describe --tags --dirty).zip"
        zip -r -j $zip_name build/*.bin build/*.elf build/bootloader/bootloader.bin build/partition_table/partition-table.bin build/flasher_args.json build/flash_args
        echo "artifact_path=$zip_name" >> "$GITHUB_ENV"

    - name: Attach files to release (${{ matrix.board }})
      uses: softprops/action-gh-release@v2
      if: ${{ github.event.release && github.event.action == 'published' }}
      with:
        files: ${{ env.artifact_path }}

    - name: Determine Size Delta (${{ matrix.board }})
      # only run this if the release is published
      if: ${{ github.event.release && github.event.action == 'published' }}
      uses: esp-cpp/esp-idf-size-delta@v1
      with:
        app_name: '${{ env.APP_NAME }} (${{ matrix.board }})'
        app_path: "."
        idf_target: ${{ matrix.target }}
        idf_version: ${{ env.IDF_VERSION }}
        idf_component_manager: ${{ env.IDF_COMPONENT_MANAGER }}
        flash_total_override: ${{ env.FLASH_TOTAL_OVERRIDE }}
        post_comment: 'false'

  package:
    name: Package the binaries into executables for Windows, MacOS, and Linux (Ubuntu)
    needs: build
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        board: ['timer-cam', 'xiao-esp32s3-sense']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: esp-cpp/esp-packaged-programmer-action@v1.0.5
        with:
          zipfile-name: build-artifacts-${{ matrix.board }}
          programmer-name: 'camera-streamer_${{ matrix.board }}_programmer'
