name: Build and Package Main

on:
  push:
    branches: [main]
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest
    continue-on-error: false

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Build Main Code
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.2.2
        target: esp32
        path: '.'

    - name: Upload Build Outputs
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: |
          build/bootloader/bootloader.bin
          build/partition_table/partition-table.bin
          build/*.bin
          build/flash_args

    - name: Attach files to release
      uses: softprops/action-gh-release@v1
      if: ${{ github.event.release && github.event.action == 'published' }}
      with:
        files: |
          build/*.bin
          build/bootloader/bootloader.bin
          build/partition_table/partition-table.bin
          build/flash_args

