name: Static analysis

on: [pull_request]

jobs:
  static_analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Run static analysis
      uses: esp-cpp/StaticAnalysis@master
      with:
        # Do not build the project and do not use cmake to generate compile_commands.json
        use_cmake: false

        # (Optional) cppcheck args
        cppcheck_args: --force --enable=all --inline-suppr --inconclusive --platform=mips32 --std=c++17 --suppressions-list=$GITHUB_WORKSPACE/suppressions.txt
